import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import CartProvider from "./_context/cart";
import AuthProvider from "./_providers/auth";

const popins = Poppins({ weight: ["400", "500", "600", "700", "800"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "FoodHub",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body className={popins.className}>
                <AuthProvider>
                    <CartProvider>{children}</CartProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
